name: quantum
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.1.4
  logger: ^2.0.2+1
  flutter_bloc: ^8.1.5
  gap: ^3.0.1
  get_it: ^7.7.0
  equatable: ^2.0.5
  shared_preferences: ^2.3.1
  cupertino_icons: ^1.0.8
  core_logic:
    git:
      url: https://github.com/Vennylost/core_logic.git
      ref: 0c0ffc39a6e10dd56b2cfe5a60478c2e2f4fa6c1

  flutter_localizations:
    sdk: flutter
  advertising_id: ^2.7.1
  syncfusion_flutter_charts: ^27.2.3
  pdf: ^3.11.1
  path_provider: ^2.1.5
  syncfusion_flutter_pdf: ^27.2.4
  printing: ^5.13.4



dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.3.0

flutter:
  uses-material-design: true
  assets:
     - assets/
     - assets/images/
     - assets/fonts/
     - assets/json/
     - assets/generated/

  fonts:
      - family: satoshi
        fonts:
          - asset: assets/fonts/satoshi.otf
            weight: 100

      - family: cygre
        fonts:
          - asset: assets/fonts/cygre-semibold.ttf
            weight: 600
          - asset: assets/fonts/cygre-medium.ttf
            weight: 500
      - family: cygre-book
        fonts:
          - asset: assets/fonts/cygre-book.ttf
            weight: 400

